=== hmcts/cpp-context-results/results-domain/results-domain-common/src/main/resources/json/schema/results.event.publish-to-dcs.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cpp/results/domain/event/results.event.publish-to-dcs.json",
  "type": "object",
  "properties": {
    "previousHearing": {
      "$ref": "http://justice.gov.uk/core/courts/hearing.json#"
    },
    "currentHearing": {
      "$ref": "http://justice.gov.uk/core/courts/hearing.json#"
    },
    "sharedTime": {
      "format": "date-time"
    },
    "hearingDay": {
      "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/datePattern"
    },
    "isReshare": {
      "type": "boolean"
    }
  },
  "required": [
    "currentHearing",
    "sharedTime",
    "hearingDay"
  ]
}

=== hmcts/cpp-context-results/results-event/results-event-processor/src/test/resources/results.event.publish-to-dcs-with-more-than-one-qaresults.json
{
  "currentHearing": {
    "courtCentre": {
      "address": {
        "address1": "176A Lavender Hill",
        "address2": "London",
        "address3": "",
        "address4": "",
        "address5": "",
        "postcode": "SW11 1JU"
      },
      "code": "B01LY00",
      "courtHearingLocation": "B01LY01",
      "id": "f8254db1-1683-483e-afb3-b87fde5a0a26",
      "lja": {
        "ljaCode": "2577",
        "ljaName": "South West London Magistrates' Court"
      },
      "name": "Lavender Hill Magistrates' Court",
      "roomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",
      "roomName": "Courtroom 01"
    },
    "defendantAttendance": [
      {
        "attendanceDays": [
          {
            "attendanceType": "NOT_PRESENT",
            "day": "2025-07-24"
          }
        ],
        "defendantId": "57bbd56a-8091-4467-9f40-a99734f99aef"
      }
    ],
    "defendantReferralReasons": [
      {
        "defendantId": "57bbd56a-8091-4467-9f40-a99734f99aef",
        "description": "Defence request",
        "id": "798e3d82-44fa-40e6-a93d-4c8f5322fa66"
      }
    ],
    "hasSharedResults": true,
    "hearingDays": [
      {
        "courtCentreId": "f8254db1-1683-483e-afb3-b87fde5a0a26",
        "courtRoomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",
        "hasSharedResults": true,
        "isCancelled": false,
        "listedDurationMinutes": 1,
        "listingSequence": 0,
        "sittingDay": "2025-07-24T10:00:00.000Z"
      },
      {
        "courtCentreId": "f8254db1-1683-483e-afb3-b87fde5a0a26",
        "courtRoomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",
        "hasSharedResults": false,
        "isCancelled": false,
        "listedDurationMinutes": 20,
        "listingSequence": 0,
        "sittingDay": "2025-07-25T09:00:00.000Z"
      },
      {
        "courtCentreId": "f8254db1-1683-483e-afb3-b87fde5a0a26",
        "courtRoomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",
        "hasSharedResults": false,
        "isCancelled": false,
        "listedDurationMinutes": 20,
        "listingSequence": 0,
        "sittingDay": "2025-07-26T09:00:00.000Z"
      },
      {
        "courtCentreId": "f8254db1-1683-483e-afb3-b87fde5a0a26",
        "courtRoomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",
        "hasSharedResults": false,
        "isCancelled": false,
        "listedDurationMinutes": 20,
        "listingSequence": 0,
        "sittingDay": "2025-07-28T09:00:00.000Z"
      },
      {
        "courtCentreId": "f8254db1-1683-483e-afb3-b87fde5a0a26",
        "courtRoomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",
        "hasSharedResults": false,
        "isCancelled": false,
        "listedDurationMinutes": 2,
        "listingSequence": 0,
        "sittingDay": "2025-07-29T14:30:00.000Z"
      }
    ],
    "hearingLanguage": "ENGLISH",
    "id": "e1698716-6899-49da-8c12-2fbe718e3009",
    "isEffectiveTrial": true,
    "isVacatedTrial": false,
    "judiciary": [
      {
        "firstName": "Christine",
        "isBenchChairman": true,
        "isDeputy": true,
        "judicialId": "0fc170ec-bb8f-31af-b2c6-de48ea5343e7",
        "judicialRoleType": {
          "judicialRoleTypeId": "0fc170ec-bb8f-31af-b2c6-de48ea5343e7",
          "judiciaryType": "Magistrate"
        },
        "lastName": "Marsters",
        "title": "Ms"
      }
    ],
    "jurisdictionType": "MAGISTRATES",
    "prosecutionCases": [
      {
        "caseStatus": "SJP_REFERRAL",
        "defendants": [
          {
            "courtProceedingsInitiated": "2025-07-24T08:57:24.321Z",
            "id": "57bbd56a-8091-4467-9f40-a99734f99aef",
            "isYouth": false,
            "masterDefendantId": "57bbd56a-8091-4467-9f40-a99734f99aef",
            "numberOfPreviousConvictionsCited": 3,
            "offences": [
              {
                "chargeDate": "2016-01-01",
                "count": 1,
                "custodyTimeLimit": {
                  "isCtlExtended": false,
                  "timeLimit": "2025-07-24"
                },
                "dateHeldInCustodySince": "2025-07-24",
                "dvlaOffenceCode": "TS30",
                "endorsableFlag": true,
                "id": "5f31119e-c72c-4bf3-820c-546ee2838c0b",
                "isDisposed": false,
                "judicialResults": [
                  {
                    "alwaysPublished": true,
                    "canBeSubjectOfBreach": false,
                    "canBeSubjectOfVariation": false,
                    "canExtendActiveOrder": false,
                    "category": "INTERMEDIARY",
                    "cjsCode": "4560",
                    "committedToCC": false,
                    "courtClerk": {
                      "firstName": "Erica",
                      "lastName": "Wilson",
                      "userId": "a085e359-6069-4694-8820-7810e7dfe762"
                    },
                    "d20": false,
                    "excludedFromResults": false,
                    "isAdjournmentResult": false,
                    "isAvailableForCourtExtract": true,
                    "isConvictedResult": false,
                    "isDeleted": false,
                    "isFinancialResult": false,
                    "isNewAmendment": true,
                    "isUnscheduled": false,
                    "judicialResultId": "c2b8912a-ea6f-4619-8b0d-ab279d6bd74e",
                    "judicialResultPrompts": [
                      {
                        "courtExtract": "Y",
                        "judicialResultPromptTypeId": "70c98fa6-804d-11e8-adc0-fa7ae01bbebc",
                        "label": "Next hearing in magistrates' court",
                        "promptReference": "0f4dba00-169b-4df2-bb65-729a21f65777",
                        "promptSequence": 0,
                        "usergroups": [],
                        "value": "Date of hearing:24/07/2025\nTime of hearing:10:00\nCourthouse organisation name:City of London Magistrates' Court\nCourthouse address line 1:1 Queen Victoria Street\nCourthouse address line 2:London\nCourthouse post code:EC4N 4XY\nCourtroom:Courtroom 01\nHearing type:Trial - no witnesses\nEstimated duration:20 MINUTES\nBooking reference:efde7aac-b775-43cc-9c06-37eb268157f7",
                        "welshLabel": "Ni wnaeth y Llys barhau â’r treial yn absenoldeb y diffynnydd"
                      },
                      {
                        "courtExtract": "N",
                        "isFinancialImposition": false,
                        "judicialResultPromptTypeId": "2d6330a2-1f12-45fb-bb72-65f4c1215e9c",
                        "label": "Prison organisation name",
                        "promptReference": "prisonOrganisationName",
                        "promptSequence": 300,
                        "type": "NAMEADDRESS",
                        "usergroups": [],
                        "value": "HMP Birmingham",
                        "welshValue": "HMP Birmingham"
                      },
                      {
                        "courtExtract": "N",
                        "isFinancialImposition": false,
                        "judicialResultPromptTypeId": "2d6330a2-1f12-45fb-bb72-65f4c1215e9c",
                        "label": "Prison email address 1",
                        "promptReference": "prisonEmailAddress1",
                        "promptSequence": 300,
                        "type": "NAMEADDRESS",
                        "usergroups": [],
                        "value": "Custody.Birmingham@justice.gov.uk",
                        "welshValue": "Custody.Birmingham@justice.gov.uk"
                      },
                      {
                        "courtExtract": "N",
                        "isFinancialImposition": false,
                        "judicialResultPromptTypeId": "2d6330a2-1f12-45fb-bb72-65f4c1215e9c",
                        "label": "Prison email address 2",
                        "promptReference": "prisonEmailAddress2",
                        "promptSequence": 300,
                        "type": "NAMEADDRESS",
                        "usergroups": [],
                        "value": "Reception.Birmingham@justice.gov.uk",
                        "welshValue": "Reception.Birmingham@justice.gov.uk"
                      },
                      {
                        "courtExtract": "N",
                        "isFinancialImposition": false,
                        "judicialResultPromptTypeId": "6927b6ac-4c85-4532-838d-88ac00ea83f9",
                        "label": "Conveyor / custodian name organisation name",
                        "promptReference": "conveyorcustodiannameOrganisationName",
                        "promptSequence": 400,
                        "type": "NAMEADDRESS",
                        "usergroups": [],
                        "value": "Banbury Magistrates' Court: PECS",
                        "welshValue": "Banbury Magistrates' Court: PECS"
                      },
                      {
                        "courtExtract": "N",
                        "isFinancialImposition": false,
                        "judicialResultPromptTypeId": "6927b6ac-4c85-4532-838d-88ac00ea83f9",
                        "label": "Conveyor / custodian name email address 1",
                        "promptReference": "conveyorcustodiannameEmailAddress1",
                        "promptSequence": 400,
                        "type": "NAMEADDRESS",
                        "usergroups": [],
                        "value": "banburymc@geoamey.co.uk",
                        "welshValue": "banburymc@geoamey.co.uk"
                      },
                      {
                        "courtExtract": "Y",
                        "isFinancialImposition": false,
                        "judicialResultPromptTypeId": "49f9ee68-3dee-4ed1-8020-377818c3697f",
                        "label": "Remand basis",
                        "promptReference": "remandBasis",
                        "promptSequence": 500,
