=== hmcts/cpp-context-results/results-domain/results-domain-common/src/main/resources/json/schema/results.event.marked-aggregate-send-email-when-account-received.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cpp/results/domain/event/marked-aggregate-send-email-when-account-received.json",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "accountCorrelationId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "oldAccountCorrelationId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "gobAccountNumber": {
      "type": "string"
    },
    "divisionCode": {
      "type": "string"
    },
    "caseReferences": {
      "type": "string"
    },
    "hearingSittingDay": {
      "type": "string"
    },
    "hearingCourtCentreName": {
      "type": "string"
    },
    "masterDefendantId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "listedDate": {
      "type": "string",
      "description": "This will passed only for statutory declaration, reopen or appeal"
    },
    "dateDecisionMade": {
      "type": "string",
      "description": "The date when hearing was resulted"
    },
    "defendantName": {
      "type": "string"
    },
    "defendantDateOfBirth": {
      "type": "string",
      "format": "date"
    },
    "isFinancialPenaltiesWrittenOff": {
      "type": "string"
    },
    "originalDateOfOffence": {
      "type": "string"
    },
    "originalDateOfSentence": {
      "type": "string"
    },
    "defendantAddress": {
      "type": "string"
    },
    "defendantEmail": {
      "type": "string",
      "format": "email"
    },
    "defendantContactNumber": {
      "type": "string"
    },
    "isSJPHearing": {
      "type": "boolean"
    },
    "applicationResult": {
      "type": "string"
    },
    "impositionOffenceDetails": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/offenceResults"
      }
    },
    "newOffenceByResult": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/offenceResults"
      }
    },
    "originalApplicationResults": {
      "$ref": "#/definitions/applicationResults"
    },
    "newApplicationResults": {
      "$ref": "#/definitions/applicationResults"
    },
    "subject": {
      "type": "string"
    },
    "sendTo": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/email"
    },
    "oldGobAccountNumber": {
      "type": "string"
    },
    "oldDivisionCode": {
      "type": "string"
    },
    "amendmentReason": {
      "type": "string",
      "description": "This will passed only for when there is amend and re-share"
    },
    "amendmentDate": {
      "type": "string",
      "description": "This will passed only for when there is amend and re-share"
    }
  },
  "definitions": {
    "offenceResults": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "offenceId": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "offenceDate": {
          "type": "string"
        },
        "details": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "applicationResults": {
      "type": "object",
      "properties": {
        "applicationTitle": {
          "type": "string"
        },
        "applicationResult": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "accountCorrelationId",
    "sendTo",
    "subject",
    "defendantName",
    "caseReferences",
    "masterDefendantId"
  ]
}

=== hmcts/cpp-context-results/results-domain/results-domain-aggregate/src/test/resources/json/nces/sjp/reopen-application/cc-case-resulted-expected-event_6.json
{
  "accountCorrelationId": "22c39541-e8e0-45b3-af99-532b33646b69",
  "caseReferences": "SJ914887739",
  "dateDecisionMade": "2026-01-20",
  "defendantAddress": "FLAT - 25A Constable Street Bristol England UK IG1 1YY",
  "defendantContactNumber": "01231231230",
  "defendantDateOfBirth": "2000-01-01",
  "defendantEmail": "Flmaq4DcSmithHaean@email.com",
  "defendantName": "Flmaq4Dc SmithHaean",
  "divisionCode": "77",
  "hearingCourtCentreName": "Lavender Hill Magistrates' Court",
  "hearingSittingDay": "2026-01-20",
  "id": "1af48e5d-c6f0-4d79-868f-485e214c21e7",
  "impositionOffenceDetails": [
    {
      "details": "A - Adjournment\nAdjourned for hearing on 20/01/2026 at 22:30 in Courtroom 01, Bexley Magistrates' Court. Reason: To attend or a warrant to issue. Defendant to attend the next hearing.\nTo attend or a warrant to issue\nhearing on 20/01/2026 at 22:30 in Courtroom 01, Bexley Magistrates' Court",
      "offenceDate": "2019-11-28",
      "offenceId": "fc813bf3-d073-4f58-b113-0ffaf7d08fd4",
      "title": "Keep a vehicle without a valid vehicle licence"
    }
  ],
  "isFinancialPenaltiesWrittenOff": "false",
  "isSJPHearing": false,
  "masterDefendantId": "34431e2d-7a41-4130-bc5f-4efa7d2d7635",
  "newApplicationResults": {
    "applicationResult": []
  },
  "newOffenceByResult": [],
  "oldAccountCorrelationId": "d39a8389-0bd5-40af-8985-260e13c18e05",
  "oldDivisionCode": "77",
  "originalDateOfOffence": "2021-21-21",
  "originalDateOfSentence": "2021-21-21",
  "sendTo": "LCCCCancellations@Justice.gov.uk",
  "subject": "APPLICATION TO REOPEN GRANTED"
}
