=== hmcts/cpp-context-results/results-event/results-event-processor/src/yaml/json/schema/public.results.police-result-generated.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cpp/results/domain/public.police-result-generated.json",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "sessionDays": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "http://justice.gov.uk/core/courts/sessionDay.json"
      }
    },
    "courtCentreWithLJA": {
      "$ref": "http://justice.gov.uk/core/courts/courtCentreWithLJA.json"
    },
    "caseId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "urn": {
      "type": "string"
    },
    "defendant": {
      "type": "object",
      "$ref": "http://justice.gov.uk/core/courts/caseDefendant.json"
    }
  },
  "required": [
    "id",
    "sessionDays",
    "courtCentreWithLJA",
    "caseId",
    "urn",
    "defendant"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-results/results-command/results-command-handler/src/test/resources/json/multi-case-defendant-amendment-add-remove-update/police-result-generated-2.json
{
  "caseId": "4c0ef53e-1110-4fe4-8378-9655ec6c8534",
  "courtCentreWithLJA": {
    "courtCentre": {
      "address": {
        "address1": "176A Lavender Hill",
        "address2": "London",
        "address3": "",
        "address4": "",
        "address5": "",
        "postcode": "SW11 1JU"
      },
      "code": "B01LY00",
      "courtHearingLocation": "B01LY01",
      "id": "f8254db1-1683-483e-afb3-b87fde5a0a26",
      "lja": {
        "ljaCode": "2577",
        "ljaName": "South West London Magistrates' Court"
      },
      "name": "Lavender Hill Magistrates' Court",
      "roomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8",
      "roomName": "Courtroom 01"
    },
    "courtHearingLocation": "B01LY01",
    "psaCode": 2577
  },
  "defendant": {
    "associatedPerson": [],
    "attendanceDays": [
      {
        "attendanceType": "NOT_PRESENT",
        "day": "2024-09-23"
      }
    ],
    "defendantId": "3c70936b-2684-4e06-b49c-4b3e99d9d65b",
    "individualDefendant": {
      "bailConditions": "",
      "bailStatus": {
        "code": "C",
        "description": "Custody",
        "id": "12e69486-4d01-3403-a50a-7419ca040635"
      },
      "person": {
        "address": {
          "address1": "9999A9999AAAA",
          "address2": "Woodlane",
          "address3": "addressline 3",
          "address4": "Bristol",
          "address5": "Avon"
        },
        "contact": {
          "home": "0202043536",
          "mobile": "07772043536",
          "primaryEmail": "REDDY.TEST012043536@gmail.com"
        },
        "dateOfBirth": "1989-12-23",
        "firstName": "Samit",
        "gender": "MALE",
        "lastName": "Patel",
        "title": "Mr"
      },
      "presentAtHearing": "N"
    },
    "offences": [
      {
        "arrestDate": "2022-10-28",
        "chargeDate": "2022-10-28",
        "finalDisposal": "N",
        "id": "849f0c07-01c8-4a58-85b2-7fd07ac78863",
        "judicialResults": [
          {
            "alwaysPublished": true,
            "canBeSubjectOfBreach": false,
            "canBeSubjectOfVariation": false,
            "category": "ANCILLARY",
            "cjsCode": "3117",
            "courtClerk": {
              "firstName": "Evan",
              "lastName": "Roberts",
              "userId": "9a84122a-c561-4229-b8ed-01bf089a877c"
            },
            "d20": false,
            "excludedFromResults": false,
            "isAdjournmentResult": false,
            "isAvailableForCourtExtract": true,
            "isConvictedResult": true,
            "isDeleted": false,
            "isFinancialResult": true,
            "isNewAmendment": true,
            "isUnscheduled": false,
            "judicialResultId": "2037791e-4f37-457d-bfa0-d168c4d6e763",
            "judicialResultPrompts": [
              {
                "courtExtract": "Y",
                "isFinancialImposition": true,
                "judicialResultPromptTypeId": "629a971e-9d7a-4526-838d-0a4cb922b5cb",
                "label": "Amount of surcharge",
                "promptReference": "AOS",
                "promptSequence": 100,
                "type": "CURR",
                "usergroups": [],
                "value": "£250.00",
                "welshLabel": "Swm y gordal",
                "welshValue": "£250.00"
              }
            ],
            "judicialResultTypeId": "e866cd11-6073-4fdf-a229-51c9d694e1d0",
            "label": "Surcharge",
            "lastSharedDateTime": "2024-09-23",
            "level": "D",
            "lifeDuration": false,
            "offenceId": "849f0c07-01c8-4a58-85b2-7fd07ac78863",
            "orderedDate": "2024-09-23",
            "orderedHearingId": "c3ba214a-18ae-49bc-bf28-8b3beab020d7",
            "postHearingCustodyStatus": "A",
            "publishedAsAPrompt": false,
            "publishedForNows": false,
            "rank": 1100,
            "resultDefinitionGroup": "Imposition",
            "resultText": "FVS - Surcharge\nTo pay a surcharge of £250.00",
            "rollUpPrompts": false,
            "rootJudicialResultId": "2037791e-4f37-457d-bfa0-d168c4d6e763",
            "rootJudicialResultTypeId": "e866cd11-6073-4fdf-a229-51c9d694e1d0",
            "terminatesOffenceProceedings": false,
            "urgent": false,
            "usergroups": [],
            "welshLabel": "Gordal"
          },
          {
            "alwaysPublished": true,
            "canBeSubjectOfBreach": false,
            "canBeSubjectOfVariation": false,
            "category": "FINAL",
            "courtClerk": {
              "firstName": "Evan",
              "lastName": "Roberts",
              "userId": "9a84122a-c561-4229-b8ed-01bf089a877c"
            },
            "d20": false,
            "excludedFromResults": false,
            "isAdjournmentResult": false,
            "isAvailableForCourtExtract": true,
            "isConvictedResult": false,
            "isDeleted": false,
            "isFinancialResult": false,
            "isNewAmendment": true,
            "isUnscheduled": false,
            "judicialResultId": "6c905ddc-9fa7-4472-bc28-335f39873434",
            "judicialResultPrompts": [
              {
                "courtExtract": "Y",
                "isFinancialImposition": false,
                "judicialResultPromptTypeId": "8e235a65-5ea2-4fff-ba3b-6cdb74195436",
                "label": "Lump sum amount",
                "promptReference": "LSA",
                "promptSequence": 100,
                "type": "CURR",
                "usergroups": [],
                "value": "£250.00",
                "welshLabel": "Swm y Cyfandaliad",
                "welshValue": "£250.00"
              },
              {
                "courtExtract": "Y",
                "isFinancialImposition": false,
                "judicialResultPromptTypeId": "1393acda-7a35-4d65-859d-6298e1470cf1",
                "label": "Instalment amount",
                "promptReference": "IAMT",
                "promptSequence": 200,
                "type": "CURR",
                "usergroups": [],
                "value": "£100.00",
                "welshLabel": "Swm y Rhandaliad",
                "welshValue": "£100.00"
              },
              {
                "courtExtract": "Y",
                "isFinancialImposition": false,
                "judicialResultPromptTypeId": "fb4f761c-29d0-4a8e-a947-3debf281dab0",
                "label": "Payment frequency following lump sum",
                "promptReference": "PF",
                "promptSequence": 300,
                "type": "FIXL",
                "usergroups": [],
                "value": "fortnightly",
                "welshLabel": "Amlder y taliadau yn dilyn y cyfandaliad",
                "welshValue": "pob pythefnos"
              },
              {
                "courtExtract": "Y",
                "isFinancialImposition": false,
                "judicialResultPromptTypeId": "b487696e-dfc9-4c89-80d3-337a4319e925",
                "label": "Instalment start date",
                "promptReference": "instalmentStartDate",
                "promptSequence": 400,
                "type": "DATE",
                "usergroups": [],
                "value": "23/12/2024",
                "welshLabel": "Dyddiad cychwyn y rhandaliadau",
                "welshValue": "23/12/2024"
              }
            ],
            "judicialResultTypeId": "272d1ec2-634b-11e8-adc0-fa7ae01bbebc",
            "label": "Payment terms - Lump sum plus instalments",
            "lastSharedDateTime": "2024-09-23",
            "level": "D",
            "lifeDuration": false,
            "offenceId": "849f0c07-01c8-4a58-85b2-7fd07ac78863",
            "orderedDate": "2024-09-23",
            "orderedHearingId": "c3ba214a-18ae-49bc-bf28-8b3beab020d7",
            "parentJudicialResultId": "68276b68-ecbe-4d37-b00a-590b861e1889",
            "parentJudicialResultTypeId": "4fdd9548-c521-48c9-baa3-1bd2f13a4fcc",
            "postHearingCustodyStatus": "A",
            "publishedAsAPrompt": false,
            "publishedForNows": false,
            "rank": 193100,
            "resultDefinitionGroup": "Payment terms",
            "resultText": "LUMSI - Payment terms - Lump sum plus instalments\nPayment terms - Lump sum plus instalments. Lump sum amount: £250.00. Instalment amount: £100.00 to be paid fortnightly from 23/12/2024.",
            "rollUpPrompts": false,
            "rootJudicialResultId": "2037791e-4f37-457d-bfa0-d168c4d6e763",
            "rootJudicialResultTypeId": "e866cd11-6073-4fdf-a229-51c9d694e1d0",
            "terminatesOffenceProceedings": false,
            "urgent": false,
            "usergroups": [],
            "welshLabel": "Telerau talu - Cyfandaliad a rhandaliadau"
          }
        ],
        "modeOfTrial": "Summary",
        "offenceCode": "CA03013",
        "offenceDateCode": 1,
        "offenceSequenceNumber": 1,
        "startDate": "2022-10-28",
        "wording": "Test Theft of pedal cycle."
      }
    ],
    "prosecutorReference": "547215884133616830"
  },
  "id": "c3ba214a-18ae-49bc-bf28-8b3beab020d7",
  "sessionDays": [
    {
      "listedDurationMinutes": 20,
      "listingSequence": 0,
      "sittingDay": "2024-09-23T11:00:00.000Z"
    }
  ],
  "urn": "20NX2043536"
}
